language: python
python:  
  - "3.6" 

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls
services:
  - postgresql
before_script:
  - psql -c "create database test_db;" -U postgres
  - export DATABASE=test_db
  
script:
 - pytest --cov=./ 
after_success:
- coveralls